name: hello-r2d2
version: 2018
summary: This cool hello world is brought to you from R2D2
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

confinement: strict

apps:
  hello-bosch:
    command: bin/hello

parts:
  first-part:
    plugin: autotools
    source: http://ftp.gnu.org/gnu/hello/hello-2.10.tar.gz
